title: Ruth García
logo: "/images/logo.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Well hello there... I am a generalist game developer.
  <br>
  Actually, I am a gameplay developer, but, when it comes to programming, I can make other things too (things like UI, animations and a teeny-tiny bit of multiplayer and AI programming). I can also make 2D and 3D art and integrate it into Unity (does that make me a junior technical artist? :O). I can also improvise sound effects and make them sound cool in Unity.
  <br>
  Do you want to know more about my adventures on the laboral world? <a href="https://www.linkedin.com/in/pr00thmatic/">Check My LinkedIn Profile!</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
