title: Ruth García
logo: "/images/logo.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Well hello there... I am a generalist game developer.
  <br>
  I am a gameplay developer, but I can make other things too (like UI, animations and a teeny-tiny bit of multiplayer and AI programming). I can also make 2D and 3D art and integrate it into Unity. I can also improvise sound effects.
  <br>
  Do you want to know more about my adventures on the laboral world? <a href="https://www.linkedin.com/in/pr00thmatic/">Check My LinkedIn Profile!</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
